### ISSUE TITLE
Error occurred when fetching container

### ISSUE THREAD

**Issue by felipel1292** [gpouilloux/gnome-shell-extension-docker#11]
Ubuntu 16.10
Docker version 17.04.0-ce, build 4845c56
GNOME Shell 3.20.4

I already tried docker ps -a --format '{{.Names}},{{.Status}}' and it works without a problem.

What can I do?

**Comment by gpouilloux** [comment]
The only command the extension run to fetch the list of containers is this
one. If the command returns 0 (success), then it appends the containers in
the dropdown menu. Otherwise, it displays the error message you got. So,
the command failed.

Potential issues:
- the user you did run this command is not the same as the one running the
Gnome extension (i.e. current session)
- you did run the command with sudo. The extension run this command with
the current user
- your current user is not part of the docker group (unix group)

**Comment by felipel1292** [comment]
I had a problem with the docker group. Thank you for the response.
