### ISSUE TITLE
Extension UI is blocked during docker operations

### ISSUE THREAD

**Issue by wyqydsyq** [gpouilloux/gnome-shell-extension-docker#23]
For example if I remove a container, the icon for this extension becomes unresponsive until the remove operation is complete. This can result in an unresponsive / clunky feeling UX.

[Video](https://i.imgur.com/kYI3Ovf.gifv)

**Comment by jagibson** [comment]
I've noticed something similar.  When starting it's only frozen for about a quarter of a second which is no biggie, but when stopping a container my entire desktop (including the mouse) is frozen for 10 seconds.

Ubuntu 18.04 / gnome shell 3.28.1 / Docker 17.12.1-ce

**Comment by ziggy42** [comment]
I'm not a GNOME expert but from my understanding this is due to the fact that extensions and the shell run on the same thread. Javascript is also single threaded so I don't think there's a way to avoid this problem, since `docker stop` just take a lot of time to finish.

A solution could be to start using the actual docker HTTP API to do things with it, if they're async, but I'm not sure about it either.
